### ISSUE TITLE
StateStore Configuration

### ISSUE THREAD

**Issue by dmpour23** [bakdata/fluent-kafka-streams-tests#17]
If I add a state store with a SpecificAvroSede as a value. How do I register it with the Test Topoloogy or point it to the SchemaRegistryMock. When I try to storeit i get...e 

`Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.NullPointerException
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl`

**Comment by AHeise** [comment]
Hi @dmpour23 , 

can you share a bit more information? The stacktrace is not even showing any line number.

My wild guess is that the schemaRegistry in that serializer is null, which would happen if the configure method of the serializer is not invoked.

Usually, if you manually create a serde instance, you need to explicitly call configure (also to tell the serde if it's used for key or value). If you didn't create serde manually, please paste a snippet of your code and test.

**Comment by AHeise** [comment]
Closing until more information come around.
