### ISSUE TITLE
Schema Registry List and Get subject versions

### ISSUE THREAD

**Issue by cricket007** [bakdata/fluent-kafka-streams-tests#19]
I would like to be able register multiple schemas under a subject, and know about their evolution. 

Add ability to perform

```
GET /subjects/:name/versions/
GET /subjects/:name/versions/:versionId
GET /subjects/:name/versions/latest
```

**Comment by AHeise** [comment]
Hi @cricket007 ,

thank you very much for this PR. Looks very good already. I just added two smaller comments.

Looking forward to merge and release it.

Best,

Arvid
