### ISSUE TITLE
[schema-registry] Use with Java 8 tests

### ISSUE THREAD

**Issue by cricket007** [bakdata/fluent-kafka-streams-tests#21]
I tried to use this library in Java 8 code, as most processes I work with still have not upgraded, but it complained that I would have to compile against Java 11 myself by including this. 

I haven't researched much on it, but is that something that adding modules can solve, or would there have to be a separately maintained release that compiled against Java 8?

Note: Kafka itself didn't move to Java 11 until 2.2.0 release.

**Comment by AHeise** [comment]
Are you referring to the Kafka Streams test framework or the schema registry mock?

The test framework uses a few newer JDK functions that could be replaced. 
Schema registry mock would probably work if I just decrease the target version.

However, Java 8 is pretty much end of life with no public updates by Oracle. So, I wouldn't like to invest much time to support it. 
If it's just for the SR mock, you could try it out in your fork with tinkering at https://github.com/bakdata/fluent-kafka-streams-tests/blob/master/build.gradle.kts#L43 . You probably want to copy that block to the build.gradle.kts of the mock subproject.

**Comment by cricket007** [comment]
I was using the SR mock.

For now, I just copied the whole class and modified the code (thus the PR). Plus, I'm using Maven, so tweaking the Gradle didn't seem like a valid option for others that might try running the tests of my own project

**Comment by AHeise** [comment]
Okay, when your PR is in. I try to set the target version to 8 before releasing it. The mock is so simple, that it should not be an issue.
