### ISSUE TITLE
Add support for JUnit4

### ISSUE THREAD

**Issue by AHeise** [bakdata/fluent-kafka-streams-tests#25]
This is a follow-up ticket to #22 .

Currently, the framework is opinionated towards JUnit4. We could broaden the scope by refactoring out the JUnit5 specific parts. 

However, I first would like to see an actual demand. So please upvote if needed.

**Comment by CliffWheadon** [comment]
I am currently trying to integrate this with a Spring-Boot/Spring-Kafka application, which wants to use JUnit 4.12, so I am very interested in seeing an instance of MockSchemaRegistry that extends something like [External Resource](https://junit.org/junit4/javadoc/4.12/org/junit/rules/ExternalResource.html#before())

**Comment by AHeise** [comment]
I started working on this and will provide a version next week.

I basically extracted all junit5 specific code into sub-modules and currently adding junit4 implementation. So it's pretty far already and it will break stuff (but with minimal effort to fix).
