### ISSUE TITLE
[schema-registry] MockedSchemaRegistry 5.2.1 returns Schema id -1 for some Schema registrations

### ISSUE THREAD

**Issue by PHameete** [bakdata/fluent-kafka-streams-tests#28]
After upgrading to confluent version 5.2.1 we ran into some issues with our test code:

Some schemas were getting version -1 on registration, causing wrong SpecificAvroSerdes to be used for deserialization.

The bug seems to be introduced here in confluent schema-registry version 5.2.0:

https://github.com/confluentinc/schema-registry/commit/a94cfd79178617ddbb23012c98d80124cc7e30b2

And solved here in confluent schema-registry version 5.2.2-rc3:

https://github.com/confluentinc/schema-registry/commit/f1d6d42ca729ac96ca4cf8711897dbe7e48908ee#diff-e5caaf947bc9ff275003783d5d50eee6

Id like to suggest to downgrade the schema-registry dependency to 5.1.3 until 5.2.2 has been released so users don't have this issue out of the box.

**Comment by AHeise** [comment]
Released 2.0.1. Thank you for the feedback. I'm upgrading to 5.2.2 as soon as it is avail.

**Comment by PHameete** [comment]
Cheers!

**Comment by PHameete** [comment]
@AHeise FYI version 5.2.2 of confluent libs is now out :-)
