### ISSUE TITLE
Support topic pattern

### ISSUE THREAD

**Issue by dabr-grapeup** [bakdata/fluent-kafka-streams-tests#31]
Hi,

Would it be possible to add support to topic pattern?
To be able to test behaviour like that:
`builder.stream(Pattern.compile(".*")).to("destination-topic");`

**Comment by dabr-grapeup** [comment]
FYI It's possible to achieve this with `TopologyTestDriver`.

**Comment by philipp94831** [comment]
Fixed by #61
