### ISSUE TITLE
fluent-kafka-streams-tests-junit4 for JDK 8

### ISSUE THREAD

**Issue by Tin-Nguyen** [bakdata/fluent-kafka-streams-tests#33]
Hi all,

My Kafka Streams application is using JDK 8, when I tried to use `fluent-kafka-streams-tests-junit4`, I got the error 
```
[ERROR] bad class file: /Users/tinnguyen/.m2/repository/com/bakdata/fluent-kafka-streams-tests/fluent-kafka-streams-tests-junit4/2.0.0/fluent-kafka-streams-tests-junit4-2.0.0.jar(com/bakdata/fluent_kafka_streams_tests/junit4/TestTopologyRule.class)
[ERROR] class file has wrong version 55.0, should be 52.0
```
I know it's caused by the dependency is built for JDK 11. I'm wondering if we have any build for JDK 8 on Maven repo?

**Comment by Tin-Nguyen** [comment]
@AHeise @lawben any helps from you?

**Comment by torbsto** [comment]
Hi @Tin-Nguyen,
as described in [this comment](https://github.com/bakdata/fluent-kafka-streams-tests/issues/21#issuecomment-480709608), the test framework uses a few newer JDK functions.
Thus, there is no JDK 8 version.
