### ISSUE TITLE
Upgrade Kafka, Confluent and Protobuf dependencies

### ISSUE THREAD

**Issue by milindmantri** [bakdata/fluent-kafka-streams-tests#67]
Hello Team Bakdata!

We are upgrading dependencies of our Kafka based project.
- Kafka 3.2 upgrades to M1 native supported RocksDB. [(link)](https://github.com/apache/kafka/pull/11967)
- Confluent 7.2.0 brings in Kafka 3.2 [(link)](https://docs.confluent.io/platform/current/release-notes/index.html)
- Protobuf released arm64 compatible protoc `v3.17.3` onwards. [(link)](https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3)

The current used version for Kafka is 3.1 and Confluent is 7.1.1. I would like to suggest that the project could also benefit from upgrading providing smoother experience on arm64 based M1.

I'll putting up the PR (which I have locally tested using `./gradlew test`. Is there more to testing dependencies change?

**Comment by milindmantri** [comment]
Also, thanks for the efforts on this library. We really like the abstractions it provides :)

**Comment by philipp94831** [comment]
Hi @milindmantri , usually the effort is to just bump version but sometimes there are more complex changes to the schema registry mock required. Feel free to go ahead and submit a PR

**Comment by milindmantri** [comment]
> Hi @milindmantri , usually the effort is to just bump version but sometimes there are more complex changes to the schema registry mock required. Feel free to go ahead and submit a PR

Done, #68
