### ISSUE TITLE
Version 2.8.0 no longer works with Spring Boot 3x due to the dependency of wiremock still using javax instead of jakarta

### ISSUE THREAD

**Issue by Bas83** [bakdata/fluent-kafka-streams-tests#72]
This may not be something you can do something about right now, but due to the wiremock dependency this library no longer works with Spring Boot 3.x

```
java.lang.NoClassDefFoundError: javax/servlet/DispatcherType

	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:390)
	at java.base/java.lang.Class.forName(Class.java:381)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.getServerConstructor(JettyHttpServerFactory.java:35)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.<clinit>(JettyHttpServerFactory.java:30)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.<init>(WireMockConfiguration.java:92)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig(WireMockConfiguration.java:125)
	at com.bakdata.schemaregistrymock.SchemaRegistryMock.<init>(SchemaRegistryMock.java:123)
```

That is the case even if I override the dependency for wiremock to the latest beta version:
(edit: at this point I didn't realize I had to exclude the jre-8 version that bakdata uses)

```
<dependency>
	<groupId>com.github.tomakehurst</groupId>
	<artifactId>wiremock</artifactId>
	<version>3.0.0-beta-2</version>
	<scope>test</scope>
</dependency>
```

**Comment by Bas83** [comment]
FYI the latest WireMock should fix this now, but is still in beta8.

Related issues:
https://github.com/wiremock/wiremock/issues/1928
https://github.com/wiremock/wiremock/issues/1760

Once WireMock 3.x is released, do you think it would be time-consuming to upgrade to it?

**Comment by torbsto** [comment]
Hey @Bas83, thanks for brining this to our attention. The upgrade looks pretty straightforward.

However, I noticed that wiremock recommends their standalone version when using Spring Boot. Have you tried to exclude `com.github.tomakehurst:wiremock-jre8` from the schema-registry-mock dependency and instead include `com.github.tomakehurst:wiremock-jre8-standalone` as a dependency?

**Comment by Bas83** [comment]
Hi @torbsto, thanks for your reply!

I don't have a direct dependency on the schema-registry-mock, but I have tried the following:

```
<dependency>
	<groupId>com.bakdata.fluent-kafka-streams-tests</groupId>
	<artifactId>fluent-kafka-streams-tests-junit5</artifactId>
	<version>2.8.2</version>
	<scope>test</scope>
	<exclusions>
		<exclusion>
			<groupId>com.github.tomakehurst</groupId>
			<artifactId>wiremock-jre8</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>com.github.tomakehurst</groupId>
	<artifactId>wiremock-jre8-standalone</artifactId>
	<version>2.35.0</version>
	<scope>test</scope>
</dependency>
```

Unfortunately that doesn't work, although it does give me a different error about something with the avro schemas. This may just be a problem with how those versions integrate.

Then I tried the same with the 3.0.0-beta-8 and that did work!

```
<dependency>
	<groupId>com.bakdata.fluent-kafka-streams-tests</groupId>
	<artifactId>fluent-kafka-streams-tests-junit5</artifactId>
	<version>2.8.2</version>
	<scope>test</scope>
	<exclusions>
		<exclusion>
			<groupId>com.github.tomakehurst</groupId>
			<artifactId>wiremock-jre8</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>com.github.tomakehurst</groupId>
	<artifactId>wiremock</artifactId>
	<version>3.0.0-beta-8</version>
	<scope>test</scope>
</dependency>
```

Obviously we'd prefer not to use a beta dependency but since it's a fairly long beta process and it's a only test dependency, I think we can go with this for now.

**Comment by Bas83** [comment]
I celebrated too early, using this beta does not work in all the apps we use the fluent kafka streams tests in. Possibly due to a different way of testing but I haven't figured it out yet.

**Comment by raafael911** [comment]
I encountered the same problem as @Bas83. Unfortunately your workaround doesn't help in my case. I get the follwoing exception:
```
java.lang.NoClassDefFoundError: org/apache/kafka/streams/internals/StreamsConfigUtils
	at org.apache.kafka.streams.TopologyTestDriver.<init>(TopologyTestDriver.java:326)
        ...
```
I have looked in many versions of org.pahache.kafka-streams:kafka-streams but nowhere is this class to be found.

**Comment by torbsto** [comment]
This should be fixed with https://github.com/bakdata/fluent-kafka-streams-tests/releases/tag/2.10.1. Feel free to reopen the issue if there are still any problems.
