### ISSUE TITLE
500 errors on server result in JSON serialiser exceptions rather than the expected error as the return is in HTML

### ISSUE THREAD

**Issue by MattA48** [bakdata/fluent-kafka-streams-tests#76]
When attempting to call the mock server in an kafka streams integration test I am receiving a 500 error from the server. It consists of the following headers:
HTTP/1.1 500 Server Error
Cache-Control must-revalidate,no-cache,no-store
Content-Type text/html;charset=ISO-8859-1
Content-Length 5820
Connection close

The response body in the debugger (truncated) is as follows:
```<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 java.lang.NoSuchMethodError: &apos;boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()&apos;</title>
</head>
<body><h2>HTTP ERROR 500 java.lang.NoSuchMethodError: &apos;boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()&apos;</h2>
<table>
<tr><th>URI:</th><td>/subjects/public_systest_alerting_preferences_2-value/versions</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>java.lang.NoSuchMethodError: &apos;boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()&apos;</td></tr>
<tr><th>SERVLET:</th><td>com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-76304b46</td></tr>
<tr><th>CAUSED BY:</th><td>java.lang.NoSuchMethodError: &apos;boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()&apos;</td></tr>
</table>
<h3>Caused by:</h3><pre>java.lang.NoSuchMethodError: &apos;boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()&apos;
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findSubtypes(JacksonAnnotationIntrospector.java:627)
	at com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver._collectAndResolve(StdSubtypeResolver.java:265)
	at com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver.collectAndResolveSubtypesByClass(StdSubtypeResolver.java:152)
...
```

This results in Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false') exceptions being reported back to the calling code from the schema registry library. This appears to be because it's returning HTML rather than the expected JSON.

This is using the schema-registry-mock 2.8.1 against kafka-streams 7.3.0-ce

**Comment by MattA48** [comment]
(the underlying bug was caused by Maven not resolving the Jackson libraries properly, but this took longer to figure out due to the 'true' error being masked)

**Comment by philipp94831** [comment]
@MattA48 Do you have a code snippet that gives us more context how you use the library and so we can reproduce it?

**Comment by MattA48** [comment]
I don't think I'm doing anything unusual, and this could grow quite big for a simple example.

I think the issue is mainly down to us previously needing to explicitly add jackson-databind to the pom, which meant we had to add jackson-annotations

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.14.1</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.14.1</version>
    </dependency>
    <dependency> *neeeded to fix*
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.14.1</version>
    </dependency>

but this core issue was that the REST client in kafka-streams is expecting a JSON response, but the body accompanying the 500 error was in HTML. I don't think there's anything in my project that sets anything like that. To get this 500 error you need Maven to somehow not include the classes found in jackson-annotations (particularly `failOnRepeatedNames`). I see this as buggy behaviour in Maven resolution, and if the above doesn't reproduce it then I'm not sure how to (but then Java isn't my main language)

The main pertinent parts of the tests are:
Setting up the Kafka container and streams:

    private KafkaStreams streamsApp;

    public static final String CONFLUENT_PLATFORM_VERSION = "7.0.9";

    private static final DockerImageName KAFKA_IMAGE = DockerImageName.parse("confluentinc/cp-kafka")
            .withTag(CONFLUENT_PLATFORM_VERSION);

    public static final KafkaContainer kafkaContainer = new KafkaContainer(KAFKA_IMAGE)
            .withEnv("KAFKA_TRANSACTION_STATE_LOG_MIN_ISR", "1")
            .withEnv("KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR", "1");

    @RegisterExtension
    static SchemaRegistryMockExtension schemaRegistry = new SchemaRegistryMockExtension();

    @BeforeEach
     void beforeEach() throws IOException {
        try {
            kafkaContainer.withStartupTimeout(Duration.ofMinutes(3)).start();
        } catch (Exception e) {
            throw new RuntimeException("Exception setting up Kafka in Integration tests", e);
        }

        String bootstrapServers = kafkaContainer.getBootstrapServers();
        var schemaUrl = schemaRegistry.getUrl();

        // Configure Serde to use the same mock schema registry URL
        Map<String, String> config = Map.of(
                AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, schemaUrl);

        // Create Serde used for test record keys and values
        final SpecificAvroSerde<price_assessments> pricesSerde = SerdeHelpers.getSpecificAvroSerde(config);
       ... other serdes ...

       // basically code to de-duplicate creating topics and a producer/consumer to mimic the TopologyTestDriver
        var topicFactory = new KafkaTopicFactory(bootstrapServers);
        pricesTopic = topicFactory.createInputTopic(ConfigLoader.PETCHEM_PRICE_TOPIC, Serdes.String(), pricesSerde, true);

       // the code to build the Topology in the Streams app under test
        var topologyBuilder = new TopologyBuilder(
                Clock.systemUTC(),
                schemaUrl,
                ""
        );

        var kafkaStreamsProps = new Properties();
        var streamsBootstrap = String.format("%s:%s", kafkaContainer.getHost(), kafkaContainer.getMappedPort(KAFKA_PORT));

        kafkaStreamsProps.put(StreamsConfig.APPLICATION_ID_CONFIG, "testApp");
        kafkaStreamsProps.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, streamsBootstrap);
        kafkaStreamsProps.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.StringSerde.class);
        kafkaStreamsProps.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, SpecificAvroSerde.class);
        kafkaStreamsProps.put("schema.registry.url", schemaUrl);

        var topology = topologyBuilder.createTopology();
        streamsApp = new KafkaStreams(topology, kafkaStreamsProps);
        streamsApp.start();
    }
    
The test itself just adds records to the created topics and consumes the output topic and compares against expected - nothing special.

The Streams app is reasonably straightforward using a mix of Specific, Generic and Reflection serdes, but I don't think the cause of the issue is in there

**Comment by torbsto** [comment]
Hi @MattA48, with release 2.8.2 the mock server now produces correctly formatted errors
